/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.util.ArrayList; 
import java.util.List; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JButton; 
import javax.swing.JComboBox; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel; 
import controler.m_koneksi; 
import controler.controller; 
import model.m_model;
/**
 *
 * @author Vidya
 */
public class home extends javax.swing.JFrame {
    controller marsal;
    List<m_model>Listdata = new ArrayList<>();
    

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        marsal =  new controller (this);
        marsal.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        opt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jns = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        admin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        bersih = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        snm = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        idcari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("ID Mitratel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 110, 110, 30);
        getContentPane().add(id);
        id.setBounds(170, 110, 180, 30);

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid);
        pid.setBounds(170, 150, 180, 30);

        jLabel2.setText("Project ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 150, 110, 30);
        getContentPane().add(sid);
        sid.setBounds(170, 190, 180, 30);

        jLabel3.setText("Site ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 110, 30);
        getContentPane().add(opt);
        opt.setBounds(170, 310, 180, 30);

        jLabel4.setText("Site Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 230, 110, 30);

        jLabel5.setText("Jenis");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 270, 110, 30);

        jns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "satu", "dua ", "tiga" }));
        getContentPane().add(jns);
        jns.setBounds(170, 270, 180, 30);

        jLabel6.setText("Operator");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 310, 110, 30);
        getContentPane().add(admin);
        admin.setBounds(30, 70, 110, 30);

        jLabel7.setText("ADMIN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 40, 110, 30);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(100, 440, 120, 30);

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah);
        ubah.setBounds(240, 390, 120, 30);

        bersih.setText("Bersihkan");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });
        getContentPane().add(bersih);
        bersih.setBounds(240, 440, 120, 30);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(100, 390, 120, 30);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Mitratel", "Project_ID", "Site_ID", "Site_Name", "Jenis", "Operator"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 90, 540, 430);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 380, 300, 100);
        getContentPane().add(snm);
        snm.setBounds(170, 230, 180, 30);

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari);
        cari.setBounds(920, 50, 90, 30);

        idcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcariActionPerformed(evt);
            }
        });
        getContentPane().add(idcari);
        idcari.setBounds(790, 50, 100, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 390, 350);

        setBounds(0, 0, 1055, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        marsal.SimpanData();
        marsal.isiTable();
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        marsal.Ubah();
        marsal.isiTable();
        
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        marsal.Hapus();
        marsal.isiTable();
    }//GEN-LAST:event_hapusActionPerformed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
       marsal.Reset();
    }//GEN-LAST:event_bersihActionPerformed

    private void idcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcariActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        marsal.CariKategori();
        marsal.isiTable();
    }//GEN-LAST:event_cariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         
       String user1=login.user;
       admin.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        int baris = tabel.getSelectedRow();
        if(baris != -1){
            id.setText(tabel.getValueAt(baris, 0).toString());
            pid.setText((String)tabel.getValueAt(baris,1).toString());
            sid.setText((String)tabel.getValueAt(baris,2).toString());
            snm.setText((String)tabel.getValueAt(baris,3).toString());
            jns.setSelectedItem(tabel.getValueAt(baris, 4).toString());
            opt.setText(tabel.getValueAt(baris, 5).toString());
            
            
        }
// TODO add your handling code here:
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin;
    private javax.swing.JButton bersih;
    private javax.swing.JButton cari;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idcari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jns;
    private javax.swing.JTextField opt;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField sid;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField snm;
    private javax.swing.JTable tabel;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

    public JTextField getId(){         
        return id;     }    
    public JTextField getPid(){         
        return pid;     }     
    public JTextField getSid(){         
        return sid;     }     
    public JTextField getSnm(){         
        return snm;     } 
    public JComboBox getJns(){         
        return jns;     } 
    public JTextField getOpt(){         
        return opt;     }
    public JTextField getCariKategori(){         
        return idcari;     }     
    public JButton getHapus(){         
        return hapus;     }          
    public JButton getBersih(){         
        return bersih;     }     
    public JButton getSimpan(){        
        return simpan;     }     
    public JButton getUbah(){         
        return ubah;     }        
    public JTable getTableData(){         
        return tabel;     }

    
}
